// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3pN0tUjlfhhsK6731m9Np_Y36KAZ6Kcs',
    appId: '1:1056642493461:web:ab2518225f4265484df21c',
    messagingSenderId: '1056642493461',
    projectId: 'zerocks-35efe',
    authDomain: 'zerocks-35efe.firebaseapp.com',
    storageBucket: 'zerocks-35efe.firebasestorage.app',
    measurementId: 'G-1W4GQ3ZJXE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3pN0tUjlfhhsK6731m9Np_Y36KAZ6Kcs',
    appId: '1:1056642493461:web:a2ee02bb0e83fa974df21c',
    messagingSenderId: '1056642493461',
    projectId: 'zerocks-35efe',
    authDomain: 'zerocks-35efe.firebaseapp.com',
    storageBucket: 'zerocks-35efe.firebasestorage.app',
    measurementId: 'G-2MMZSX1W3B',
  );

}